// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"
throw new Error('OMGGGGG')

import HelloController from "./hello_controller"
import InfiniteScrollController from "./infinite_scroll_controller"
console.log('Loaded');
application.register("hello", HelloController)
application.register("infinite_scroll", InfiniteScrollController)
